AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'mailer

  Sample SAM Template for mailer

  '
Globals:
  Function:
    Timeout: 3
Resources:
  ExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action: sts:AssumeRole
      Path: /
      Policies:
      - PolicyName: sendEmails
        PolicyDocument:
          Statement:
            Effect: Allow
            Action:
            - ses:SendEmail
            - ses:SendRawEmail
            Resource: '*'
  MailerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://cloudformation-stacks-test/3c76c536f85403e0e21bd6c65f2ca395
      Handler: app.lambda_handler
      Runtime: python3.7
Outputs:
  MailerFunction:
    Description: Mailer Lambda Function ARN
    Value:
      Fn::GetAtt:
      - MailerFunction
      - Arn
