AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  mailer

  Sample SAM Template for mailer

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  ExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
            - Effect: Allow
              Principal:
                Service:
                    - lambda.amazonaws.com
              Action: "sts:AssumeRole"
      Path: /
      Policies:
        - PolicyName: sendEmails
          PolicyDocument:
            Statement:
                Effect: Allow
                Action:
                    - "ses:SendEmail"
                    - "ses:SendRawEmail"
                Resource: "*"
  MailerFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: send_mail/
      Handler: app.lambda_handler
      Runtime: python3.7

Outputs:
  MailerFunction:
    Description: "Mailer Lambda Function ARN"
    Value: !GetAtt MailerFunction.Arn
